### ISSUE TITLE
Investigate Helm integration

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#1319]
* About 49% of effective organizations that use Kubernetes use [Helm](https://helm.sh/) ([Google-internal source](https://drive.google.com/file/d/16cKqaO4SIV14GULygQFiN2JPQ1rM1QPc/view?resourcekey=0-a-tUFsdjsi3iiaPkMWSkAg)).
* Part of the Online Boutique's purpose is to demonstrate tools and technologies commonly used alongside the above products.
* This makes it clear that there's a lot of value in Online Boutique demonstrating the use of Helm.
* We just need to figure out how Online Boutique can/should make use of Helm.
* Thank you, @mathieu-benoit, for this suggestion.

## TODO
This GitHub issue tracks the following work:
* [ ] Research Helm.
* [ ] Figure out if and how Online Boutique should integrate Helm.
    * [ ] Make sure it aligns with [/docs/product-requirements.md](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/product-requirements.md).
* [ ] Create a separate GitHub issue to track and detail the implementation.

**Comment by fjellvannet** [comment]
I managed to deploy the microservices-demo with scaffold in my microk8s-test-cluster, but not using helm.

I always get this error:

<img width="1631" alt="Skjermbilde 2024-06-14 kl  08 57 12" src="https://github.com/GoogleCloudPlatform/microservices-demo/assets/22413504/5aafec8c-145c-463f-b0c6-e40664875844">

It says I need to install the CRD's first. How can I do that? For skaffold that was not necessary as far as I know :)

**Comment by NimJay** [comment]
@fjellvannet could you please retry your Helm command with `--set authorizationPolicies.create=false`?
([AuthorizationPolicy](https://istio.io/latest/docs/reference/config/security/authorization-policy/) objects are a Istio concept — not a core Kubernetes concept.)

**Comment by fjellvannet** [comment]
Hello @NimJay,
I still have the same problem, even though I now put authorizationPolicies.create=false:

![bilde](https://github.com/GoogleCloudPlatform/microservices-demo/assets/22413504/e78333b7-e66b-4dbc-af53-aa68eacea759)

My microk8s cluster is pretty vanilla, not much else installed on it.

**Comment by fjellvannet** [comment]
This combination of parameters goes through:

![bilde](https://github.com/GoogleCloudPlatform/microservices-demo/assets/22413504/5ac87147-3bb2-49cc-b28d-55020cdec599)

Here, authorizationPolicies.create=false, sidecars.create=false and frontent.virtualService.create=false

However, it doesn't look particularly happy:

![bilde](https://github.com/GoogleCloudPlatform/microservices-demo/assets/22413504/f8039452-3ded-4651-8939-ac8c92d7cbe8)

This screenshot is from k9s on a vanilla microk8s installation. There seems to be a problem pulling the container images from the helmchart.

It also failed in a similar way in the cluster where the skaffold-version of the microservices-demo is already happily running.
