### ISSUE TITLE
Rebrand "Online Boutique" as "Cymbal Shops"

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#574]
## Background
* Cymbal is a **fictitious** company created by Google to be used in demo apps.
  * Cymbal Shops is a Cymbal subsidiary.
  * Cymbal Shops is an American retail chain headquartered in Minneapolis that sells homeware, electronics, and clothing. 
  * More about Cymbal can be learned [at this internal Google site](https://sites.google.com/corp/google.com/cdbsitemapgoogle/home).
* This task of rebranding is documented [in this internal Google Doc](https://docs.google.com/document/d/1VZa2bvRkPDTXwIeIvRbeOFMhQ0ILdevbCyboYNfIZgk/edit?resourcekey=0-W7CcXITijJHsfilktu2rXQ).
* The Google Cloud Demos and Experiments team has created [Figma prototypes](https://www.figma.com/file/UlhTLEvRFIw8vK5wAzD7Vq/OnlineBoutique.dev?node-id=6%3A14) (only accessible to Googlers with a Figma subscription) for the new design.

## Changes
* We will default to the "Online Boutique" wording across the app to remain backwards compatible. 
  * Users of `microservices-demo` will need to set an environment variable to update the wording from "Online Boutique" to "Cymbal" (we've done something [similar with the "Bank of Anthos"/"Cymbal Bank" demo](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/kubernetes-manifests/frontend.yaml#L50)).

###  What needs to be done?
- [x] Change the font from 'Roboto' to 'DM Sans'. (#575)
- [x] Udate UI to match the design from the aforementioned Figma prototypes. (#593)
- [x] Update items/products being sold to fit the _Cymbal Shops_ story. (#600)
- [x] Introduce an environment variable that lets us toggle the "Cymbal Shops" wording on and off (i.e., show "Online Boutique" by default). (#602)
- [x] Update documentation (e.g., the screenshots in the [README.md](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/README.md)). (#603)

**Comment by ahmetb** [comment]
Are we keeping the repo name the same? That would be ideal.

Cymbal is a bit cryptic name, hence it worries me a little bit but if it is decided, that's alright. The internal website is 404ing for me.

**Comment by NimJay** [comment]
Hello @ahmetb. 

> Are we keeping the repo name the same? 
Yes, the repo name will be the same (`microservices-demo`). :)

> Cymbal is a bit cryptic name
I agree. :)
We'll _likely_ be rebranding, more specifically, as "Cymbal Shop".

> The internal website is 404ing for me.
This is the exact URL: https://sites.google.com/corp/google.com/cdbsitemapgoogle/home

**Comment by NimJay** [comment]
The work for this issue is complete and included in release v0.3.0.
Closing.
