### ISSUE TITLE
Standardize port numbers for grpc services

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#9]
To prevent port bookkeeping across the board.

Similarly we should probably standardize port numbers across all prometheus/opencensus/pprof endpoints as well.

# TODO

- [x] find out what's the preferred port number for grpc serving in the community.
- [ ] update all gRPC services to expose the same server port 
- [ ] update Kubernetes manifests for `containerport` / match service port to container port?
- [ ] update Istio manifests

**Comment by askmeegs** [comment]
There doesn't seem to be a universal port standard for gRPC, but I am seeing a lot of `50051`  -- 

https://medium.com/engineering-semantics3/a-simplified-guide-to-grpc-in-python-6c4e25f0c506

https://www.nginx.com/blog/nginx-1-13-10-grpc/

https://github.com/datawire/ambassador/blob/master/docs/user-guide/grpc.md#dockerize

**Comment by ahmetb** [comment]
Since we support $PORT everywhere this is probably no longer needed.

**Comment by murog** [comment]
is alright if this is closed then? @ahmetb
